import { Service, Software } from "./types";

// ============================================================================
// DONNÉES STATIQUES - SERVICES
// ============================================================================

export const services: Service[] = [
  {
    icon: "💿",
    title: "Vente de Logiciels",
    description:
      "Accédez à une large gamme de logiciels professionnels et personnels à prix compétitifs.",
    features: ["Licences authentiques", "Support technique", "Mises à jour gratuites"],
  },
  {
    icon: "📚",
    title: "Formations Informatiques",
    description:
      "Des formations adaptées à votre niveau pour maîtriser les technologies actuelles.",
    features: ["Cours en ligne", "Certificats reconnus", "Formateurs expérimentés"],
  },
  {
    icon: "🛠️",
    title: "Assistance Technique",
    description:
      "Support technique 24/7 pour résoudre tous vos problèmes informatiques.",
    features: ["Assistance rapide", "Experts disponibles", "Dépannage complet"],
  },
];

// ============================================================================
// DONNÉES STATIQUES - LOGICIELS
// ============================================================================

export const softwares: Software[] = [
  {
    id: 1,
    name: "Microsoft Office 365",
    price: 99000,
    priceFormatted: "99 000 FCFA",
    category: "Bureau",
    icon: "📝",
    description: "Suite complète de productivité avec Word, Excel, PowerPoint et Outlook",
    image: "/images/office365.png",
    licenses: [
      { type: "personnel", duration: "1_an", users: 1, support: true },
      { type: "professionnel", duration: "1_an", users: 5, support: true },
      { type: "entreprise", duration: "perpetuel", users: 999, support: true },
    ],
    stock: 45,
    rating: 4.8,
    reviews: 234,
    features: ["Word", "Excel", "PowerPoint", "Outlook", "OneDrive 1TB", "Support 24/7"],
    system: "Windows, Mac, iOS, Android",
    publisher: "Microsoft",
  },
  {
    id: 2,
    name: "Adobe Creative Cloud",
    price: 54990,
    priceFormatted: "54 990 FCFA",
    category: "Design",
    icon: "🎨",
    description: "Suite professionnelle complète pour créatifs avec Photoshop, Illustrator et Premiere",
    image: "/images/adobe.png",
    licenses: [
      { type: "personnel", duration: "1_an", users: 1, support: false },
      { type: "professionnel", duration: "1_an", users: 3, support: true },
      { type: "entreprise", duration: "1_an", users: 50, support: true },
    ],
    stock: 32,
    rating: 4.9,
    reviews: 567,
    features: ["Photoshop", "Illustrator", "Premiere Pro", "After Effects", "InDesign", "Lightroom"],
    system: "Windows, Mac",
    publisher: "Adobe",
  },
  {
    id: 3,
    name: "Norton 360 Deluxe",
    price: 49000,
    priceFormatted: "49 000 FCFA",
    category: "Sécurité",
    icon: "🛡️",
    description: "Protection antivirus complète avec VPN, gestionnaire de mots de passe et contrôle parental",
    image: "/images/norton.png",
    licenses: [
      { type: "personnel", duration: "1_an", users: 5, support: true },
      { type: "personnel", duration: "perpetuel", users: 5, support: true },
    ],
    stock: 78,
    rating: 4.7,
    reviews: 892,
    features: ["Antivirus", "VPN", "Gestionnaire de mots de passe", "Contrôle parental", "Sauvegarde cloud"],
    system: "Windows, Mac, iOS, Android",
    publisher: "Norton",
  },
  {
    id: 4,
    name: "Visual Studio Code",
    price: 0,
    priceFormatted: "Gratuit",
    category: "Développement",
    icon: "💻",
    description: "Éditeur de code source gratuit et puissant pour tous les langages de programmation",
    image: "/images/vscode.png",
    licenses: [
      { type: "personnel", duration: "perpetuel", users: 999, support: false },
    ],
    stock: 999,
    rating: 4.9,
    reviews: 2341,
    features: ["Intellisense", "Extensions", "Debugging", "Git intégré", "Terminal intégré"],
    system: "Windows, Mac, Linux",
    publisher: "Microsoft",
  },
  {
    id: 5,
    name: "JetBrains IntelliJ IDEA",
    price: 179000,
    priceFormatted: "179 000 FCFA",
    category: "Développement",
    icon: "🔧",
    description: "IDE professionnel pour Java et développement multi-langages avec support avancé",
    image: "/images/intellij.png",
    licenses: [
      { type: "personnel", duration: "1_an", users: 1, support: true },
      { type: "professionnel", duration: "1_an", users: 10, support: true },
      { type: "entreprise", duration: "perpetuel", users: 999, support: true },
    ],
    stock: 28,
    rating: 4.8,
    reviews: 456,
    features: ["Java", "Kotlin", "Python", "PHP", "JavaScript", "Debugging avancé"],
    system: "Windows, Mac, Linux",
    publisher: "JetBrains",
  },
  {
    id: 6,
    name: "WinRAR",
    price: 29000,
    priceFormatted: "29 000 FCFA",
    category: "Utilitaires",
    icon: "📦",
    description: "Gestionnaire d'archives puissant pour compresser, décompresser et créer des archives",
    image: "/images/winrar.png",
    licenses: [
      { type: "personnel", duration: "perpetuel", users: 1, support: false },
      { type: "professionnel", duration: "perpetuel", users: 50, support: true },
    ],
    stock: 156,
    rating: 4.6,
    reviews: 1203,
    features: ["Compression RAR/ZIP", "Cryptage AES", "Réparation d'archives", "Interface intuitive"],
    system: "Windows, Mac, Linux",
    publisher: "WinRAR",
  },
  {
    id: 7,
    name: "Kaspersky Internet Security",
    price: 39000,
    priceFormatted: "39 000 FCFA",
    category: "Sécurité",
    icon: "🔐",
    description: "Solution de sécurité avancée contre les menaces cybernétiques et les ransomwares",
    image: "/images/kaspersky.png",
    licenses: [
      { type: "personnel", duration: "1_an", users: 3, support: true },
      { type: "professionnel", duration: "1_an", users: 20, support: true },
    ],
    stock: 91,
    rating: 4.7,
    reviews: 678,
    features: ["Antivirus", "Pare-feu", "Protection en temps réel", "Analyse comportementale"],
    system: "Windows, Mac",
    publisher: "Kaspersky",
  },
  {
    id: 8,
    name: "Sublime Text 4",
    price: 89000,
    priceFormatted: "89 000 FCFA",
    category: "Développement",
    icon: "✍️",
    description: "Éditeur de texte sophistiqué pour développeurs avec performances optimales",
    image: "/images/sublime.png",
    licenses: [
      { type: "personnel", duration: "perpetuel", users: 1, support: false },
      { type: "professionnel", duration: "perpetuel", users: 999, support: true },
    ],
    stock: 45,
    rating: 4.8,
    reviews: 834,
    features: ["Édition multi-ligne", "Snippets", "Palettes de commandes", "Plugins"],
    system: "Windows, Mac, Linux",
    publisher: "Sublime HQ",
  },
  {
    id: 9,
    name: "Bitdefender Total Security",
    price: 44000,
    priceFormatted: "44 000 FCFA",
    category: "Sécurité",
    icon: "🔒",
    description: "Protection complète avec antivirus, VPN illimité et optimisation du système",
    image: "/images/bitdefender.png",
    licenses: [
      { type: "personnel", duration: "1_an", users: 10, support: true },
      { type: "personnel", duration: "perpetuel", users: 10, support: true },
    ],
    stock: 64,
    rating: 4.9,
    reviews: 945,
    features: ["Antivirus", "VPN illimité", "Optimisation", "Anti-ransomware", "Webcam Guard"],
    system: "Windows, Mac, iOS, Android",
    publisher: "Bitdefender",
  },
  {
    id: 10,
    name: "Microsoft Windows 11 Pro",
    price: 199000,
    priceFormatted: "199 000 FCFA",
    category: "Systèmes",
    icon: "🪟",
    description: "Système d'exploitation Windows 11 Pro pour professionnels avec fonctionnalités avancées",
    image: "/images/windows11.png",
    licenses: [
      { type: "personnel", duration: "perpetuel", users: 1, support: true },
      { type: "professionnel", duration: "perpetuel", users: 999, support: true },
    ],
    stock: 38,
    rating: 4.7,
    reviews: 2105,
    features: ["Hyper-V", "BitLocker", "Domain Join", "Group Policy", "Taskbar personnalisée"],
    system: "Windows",
    publisher: "Microsoft",
  },
  {
    id: 11,
    name: "AutoCAD 2024",
    price: 149000,
    priceFormatted: "149 000 FCFA",
    category: "Design",
    icon: "📐",
    description: "Logiciel professionnel de CAO pour architecture, ingénierie et design",
    image: "/images/autocad.png",
    licenses: [
      { type: "professionnel", duration: "1_an", users: 1, support: true },
      { type: "entreprise", duration: "1_an", users: 50, support: true },
    ],
    stock: 19,
    rating: 4.8,
    reviews: 567,
    features: ["Dessin 2D/3D", "BIM", "Collaboration cloud", "API", "Mobile app"],
    system: "Windows, Mac",
    publisher: "Autodesk",
  },
  {
    id: 12,
    name: "VLC Media Player",
    price: 0,
    priceFormatted: "Gratuit",
    category: "Multimédia",
    icon: "🎬",
    description: "Lecteur multimédia gratuit et open-source supportant tous les formats vidéo et audio",
    image: "/images/vlc.png",
    licenses: [
      { type: "personnel", duration: "perpetuel", users: 999, support: false },
    ],
    stock: 999,
    rating: 4.7,
    reviews: 8934,
    features: ["Tous les formats", "Sans publicités", "Open-source", "Personnalisable"],
    system: "Windows, Mac, Linux, iOS, Android",
    publisher: "VideoLAN",
  },
];
